### PR TITLE
Get ready for rhel8 Jenkins nodes

### PR DESCRIPTION
**Pull request by mjholder**
We are migrating to running our build jobs on rhel8 nodes. 
These nodes use podman instead of docker which doesn't support `buildx` commands for multiarch support.
I commented out those lines so if/when that support comes back we can easily bring back the functionality.
ticket: https://issues.redhat.com/browse/RHCLOUD-33431

### CODE REVIEW

**Comment by adamrdrew** [comment]
LGTM but I'd like to get a second set of eyes.

**Review by Victoremepunto — COMMENTED** [review]
@mjholder @adamrdrew I have a couple of comments:
- if we want to keep multiarch, podman [seems to be able to handle it](https://developers.redhat.com/articles/2023/11/03/how-build-multi-architecture-container-images#podman). I'd ask we its worth the effort porting it ?

- if we don't care about multiarch, I'd remove the code instead of commenting it out, if we need that code we can retrieve it from the commit history anyways.

**Comment by mjholder** [comment]
> @mjholder @adamrdrew I have a couple of comments:
> 
>     * if we want to keep multiarch, podman [seems to be able to handle it](https://developers.redhat.com/articles/2023/11/03/how-build-multi-architecture-container-images#podman). I'd ask we its worth the effort porting it ?
> 
>     * if we don't care about multiarch, I'd remove the code instead of commenting it out, if we need that code we can retrieve it from the commit history anyways.

It doesn't seem like a big lift to do that but that brings up another point. I think I need to replace the docker commands with podman commands. i.e. `docker build ...` -> `podman build ...`

**Review by Victoremepunto — APPROVED** [review]
LGTM

**Pull request merged**
