### PR TITLE
When running npm ls send errors to dev null so we have correct json file

### PR DESCRIPTION
**Pull request by karelhala**

### CODE REVIEW

**Comment by gmcculloug** [comment]
This PR is a result of @karelhala helping to debug failing builds on the approval UI.

Last good build (ran for 3min 25sec): https://travis-ci.org/ManageIQ/approval-ui/builds/542459381  
Failed Build (timed out after 10min of no output): https://travis-ci.org/ManageIQ/approval-ui/builds/547233405

Same failures are happening on the [RBAC UI](https://travis-ci.org/RedHatInsights/insights-rbac-ui/branches) and [Catalog UI](https://travis-ci.org/ManageIQ/catalog-ui/branches) as well.

**Comment by karelhala** [comment]
@iphands yeah, I tried to hide them because I thought that they could be sent to the variable, looks like that's not the case. Still not sure what could cause the hang though

**Comment by Hyperkid123** [comment]
@karelhala @iphands the travis hang might be very likely caused bu the npm ls output to console. 

This might sound strange but we had similar issues with very long snapshots in certain components in cloudforms. The travis terminal was crashing(timing out) but after we skipped tests with unusually long output process finished successfully.

There is another workaround by using `travis_time` https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

**Comment by Hyperkid123** [comment]
@iphands speaking oof `npm ls` errors. We(catalog-ui, approval-ui, rbac-ui) are encountering version mismatch of peer dependnecies from `dev-dependcies` (most of the comes from jest-cli). That can be easilly fixed with `npm ls --production`

Another thing is mismatched peer dependencies between project dependencies. For instance we are using `react-router` v5.x but in one of the libraries from insights-frontend-components bundle requires v4.  Even though we are not using the component from insights-frontend-components and it does not affect our UI in any way we still get an error. I have nothing against additional dependencies check but error like this has no additional value for us.

**Comment by iphands** [comment]
We talked to the stake holder that was using the deps output (QE). They are not even using it at the moment.

Lets just comment that section out for now, we can revisit once we need to.

**Comment by iphands** [comment]
Does the `npm ls` actually take 10 mins locally though? Lets disable it right away, but Im curious as to why this is causing issues.

**Comment by iphands** [comment]
About the mismatched deps ... can you file another issue there against the IFC? @karelhala  can probably pull it in as official work

**Comment by Hyperkid123** [comment]
> Does the `npm ls` actually take 10 mins locally though? Lets disable it right away, but Im curious as to why this is causing issues.

It does not 10 minutes locally. Travis has a "feature" when the output log is too long (has too many characters) it stops the build and mark it as failed.

I created example here: https://travis-ci.org/data-driven-forms/react-forms/builds/550154589?utm_source=github_status&utm_medium=notification

It runs a test which prints out random characters. Job started failing after printing give or take 5 million characters. The `npm ls` command in catalog UI has 4226068 characters. Considering that travis runs additional jobs from different config, my guess is that the `insights-frontend-builder-common` is terminated because of output length and that times out the main build from repo.

**Comment by karelhala** [comment]
@iphands it has been commented out so I think good to merge?

**Pull request merged**
